services:
# postgres database
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - postgres-db-volume:/var/lib/postgres

# volumes configuration
volumes:
  postgres-db-volume:
    driver: local
